Semana 7/Tiago/siteiscte/siteiscte/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('votacao/', include('votacao.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Semana 7/Tiago/siteiscte/votacao/urls.py
from django.urls import include, path
from . import views

app_name = 'votacao'

urlpatterns = [
    # ex: votacao/
    path("", views.index, name='index'),
    # ex: votacao/1
    path('<int:questao_id>', views.detalhe, name='detalhe'),
    # ex: votacao/3/resultados
    path('<int:questao_id>/resultados', views.resultados, name='resultados'),
    # ex: votacao/5/voto
    path('<int:questao_id>/voto', views.voto, name='voto'),

    # criar uma nova questao
    path('criarquestao', views.criarquestao, name='criarquestao'),

    # criar nova opçao para uma questao
    path('<int:questao_id>/criaropcao', views.criaropcao, name='criaropcao'),
    # path('<int:questao_id>/adicionaropcao', views.adicionaropcao, name='adicionaropcao'),

    # remover uma questao/opcao
    path('<int:questao_id>/removerquestao', views.removerquestao, name='removerquestao'),
    path('<int:questao_id>/removeropcao', views.removeropcao, name='removeropcao'),

    path('registar', views.registaruser, name='registaruser'),
    path('login', views.loginview, name='loginview'),
    path('meu_perfil', views.perfil, name='perfil'),
    path('logout', views.logoutview, name='logoutview'),
    path('fazer_upload', views.fazer_upload, name='fazer_upload'),
]

Semana 7/Tiago/siteiscte/votacao/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
from six import string_types
import datetime
from django.contrib.auth.models import User


class Questao(models.Model):
    questao_texto = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.questao_texto

    def foi_publicada_recentemente(self):
        return self.pub_data >= timezone.now() - datetime.timedelta(days=1)


class Opcao(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.opcao_texto


class Aluno(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    curso = models.CharField(max_length=100)
    numvotos = models.IntegerField(default=0)

    def __str__(self):
        return self.curso

Semana 7/Tiago/siteiscte/votacao/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from .models import Questao, Opcao, Aluno

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage


def fazer_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'votacao/fazer_upload.html', {'uploaded_file_url': uploaded_file_url})
    return render(request, 'votacao/fazer_upload.html')


# Função para registar novo Utilizador
def registaruser(request):
    if request.method == 'POST':
        try:
            nameuser = request.POST.get('novouser')
            emailuser = request.POST.get('novouseremail')
            passworduser = request.POST.get('novouserpassword')
            cursouser = request.POST.get('novousercurso')
        except KeyError:
            return render(request, 'votacao/registar.html')

        # Verifica se já existe um utlizador
        if User.objects.filter(username=nameuser).exists():
            return render(request, 'votacao/registar.html', {
                'error_message': "Já existe um utilizador com esse nome",
            })

        # Verifica se já o curso contém no final um valor númerico
        if not (type(cursouser[-1]) is int):
            return render(request, 'votacao/registar.html', {
                'error_message': "É necessario que o curso tenha em ultimo um valor inteiro",
            })

        user = User.objects.create_user(nameuser, emailuser, passworduser)
        user.save()
        Aluno(user=user, curso=cursouser, numvotos=0).save()
        return HttpResponseRedirect(reverse('votacao:loginview'))
    else:
        return render(request, 'votacao/registar.html')


# Função para obter os dados de um Utilizador
def perfil(request):
    return render(request, 'votacao/meu_perfil.html')


# Função para fazer o login
def loginview(request):
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
        except KeyError:
            return render(request, 'votacao/login.html')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('votacao:index'))
        else:
            return render(request, 'votacao/login.html', {
                'error_message': "User e/ou password incorretos",
            })
    else:
        return render(request, 'votacao/login.html')


# Função para fazer o logout
def logoutview(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse('votacao:index'))


def criarquestao(request):
    if request.method == 'POST':
        try:
            questao_texto = request.POST.get("novaquestao")
        except KeyError:
            return render(request, 'votacao/criarquestao.html')

        if Questao.objects.filter(questao_texto=questao_texto).exists():
            return render(request, 'votacao/criarquestao.html', {
                'error_message': "Já existe essa questão",
            })

        if questao_texto:
            if request.user.is_superuser:
                questao = Questao(questao_texto=questao_texto, pub_data=timezone.now())
                questao.save()
            return HttpResponseRedirect(reverse('votacao:index'))
        else:
            return HttpResponseRedirect(reverse('votacao:criarquestao'))
    else:
        return render(request, 'votacao/criarquestao.html')


def criaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    if request.method == 'POST':
        try:
            opcao = request.POST.get('adicionaropcao')
        except KeyError:
            return render(request, 'votacao/criarquestao.html', {'questao': questao})
        if opcao:
            if request.user.is_superuser:
                if not Opcao.objects.filter(questao=questao, opcao_texto=opcao).exists():
                    novaopcao = questao.opcao_set.create(opcao_texto=opcao, votos=0)
                    novaopcao.save()
                else:
                    return render(request, 'votacao/criaropcao.html', {
                        'questao': questao, 'error_message': "Já existe essa Opção"})

            return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))
        else:
            return HttpResponseRedirect(reverse('votacao:criaropcao', args=(questao.id,)))
    else:
        return render(request, 'votacao/criaropcao.html', {'questao': questao})


def removerquestao(request, questao_id):
    if request.user.is_superuser:
        questao = get_object_or_404(Questao, pk=questao_id)
        if questao.opcao_set.count() > 0:
            for opcao in questao.opcao_set.all():
                opcao.delete()
        questao.delete()

    return HttpResponseRedirect(reverse('votacao:index'))


def removeropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'votacao/detalhe.html', {
            'questao': questao,
            'error_message': "Não escolheu uma opção",
        })
    else:
        if request.user.is_superuser:
            opcao_seleccionada.delete()
    return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))


# Função para o Index
# criar condiçao para ser reencaminhado para o login
def index(request):
    latest_question_list = Questao.objects.order_by('-pub_data')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'votacao/index.html', context)


# Função para obter as opções de votos numa questão
def detalhe(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/detalhe.html', {'questao': questao})


# Função para obter os número de cada voto numa questão após ser feita um novo voto
def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)

    return render(request, 'votacao/resultados.html', {'questao': questao})


# Função para obter adicionar um voto numa questão
def voto(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html', {
            'questao': questao,
            'error_message': "Não escolheu uma opção",
        })
    else:
        if request.user.is_authenticated:
            if request.user.aluno.numvotos >= int(request.user.aluno.curso[-1]) + 5:
                return render(request, 'votacao/detalhe.html', {
                    'questao': questao,
                    'error_message': "Limite de votos excedido",
                })

            opcao_seleccionada.votos += 1
            opcao_seleccionada.save()
            request.user.aluno.numvotos += 1
            request.user.aluno.save()
        else:
            return render(request, 'votacao/detalhe.html', {
                'questao': questao,
                'error_message': "Utilizador não se encontra Autenticado",
            })

    return HttpResponseRedirect(
        reverse('votacao:resultados', args=(questao.id,)))

Semana 7/Tiago/siteiscte/votacao/templates/votacao/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'votacao/style.css' %}" />
<!-- Index,detalhe, opcao, questao, upload, resultado-->

<div id="base_body">
    {% block base_body %}

    <header>
        <table>
    <tr>
        <th><h1>SiteIscte</h1></th>
        <th></th>

        {% if request.user.is_authenticated %}
            <th><img src="{% static "votacao/images/iscte.jpeg" %}"></th>
            <th>
            {% if request.user.is_superuser %}
                <p>{{request.user.username}} (Adiministrador)</p>
                {% else %}
                <p>{{request.user.username}} (Utilizador)</p>
            {% endif %}
                <p>Número votos realizados (total): {{request.user.aluno.numvotos}}</p>
            </th>
        {% endif %}

    </tr>
    </table>
    </header>
    <nav class="container">

    <table>
    {% if request.user.is_authenticated %}

            <tr><a href="{% url 'votacao:perfil' %}">Meu Perfil</a></tr>
            <tr><a href="{% url 'votacao:logoutview' %}">Logout</a></tr>

        {% else %}
            <tr><a href="{% url 'votacao:loginview' %}">Login</a></tr>
            <tr><a href="{% url 'votacao:registaruser' %}">Registar-se</a></tr>
    {% endif %}
    </table>

</nav>
{% endblock %}
</div>

<!-- Login, registar-->
<div id="base_login_registar">
    {% block base_login_registar %}
    <header>
        <h1>SiteIscte</h1>
    </header>
    {% endblock %}
</div>

<!-- Perfil-->

<div id="base_perfil">
    {% block base_perfil %}
        <header>
        <table>
    <tr>
        <th><h1>SiteIscte</h1></th>
        <th></th>

        {% if request.user.is_authenticated %}
            <th><img src="{% static "votacao/images/iscte.jpeg" %}"></th>
        {% endif %}

    </tr>
    </table>
    </header>
    <nav class="container">

    <table>
    {% if request.user.is_authenticated %}
        <tr><a href="{% url 'votacao:logoutview' %}">Logout</a></tr>
        {% else %}
    {% endif %}
    </table>

</nav>
    {% endblock %}
</div>

<div id="base_index">
    {% block base_index %}
    {% endblock %}
</div>

</body>
</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/criaropcao.html
<!DOCTYPE html>
{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block base_perfil %}
{% endblock %}
{% block base_login_registar %}
    {% endblock %}
{% block base_index %}

<h1>Adicionar uma nova opcao</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'votacao:criaropcao' questao.id %}" method="post">
    {% csrf_token %}
    <label>Escreva uma opçao: </label>
    <br>
    <input type="text" name="adicionaropcao" required/>
    <br/><br/>
    <input type="submit" value="Guardar Opcao" />
</form>

<ul>
    <a href="{% url 'votacao:detalhe' questao.id %}">Retornar ao Questão</a>
    <br>
    <a href="{% url 'votacao:index' %}">Retornar ao Index</a>
</ul>

{% endblock %}

</body>
</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/criarquestao.html
<!DOCTYPE html>
{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block base_perfil %}
{% endblock %}
{% block base_login_registar %}
    {% endblock %}
{% block base_index %}

<h1>Adicionar uma nova questao</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'votacao:criarquestao' %}" method="post">
    {% csrf_token %}
    <label>Escreva uma pergunta: </label>
    <br>
    <input type="text" name="novaquestao" required/>
    <br/><br>
    <input type="submit" value="Guardar Questao"/>
</form>
<ul>
    <a href="{% url 'votacao:index' %}">Retornar ao Index</a>
</ul>
{% endblock %}
</body>
</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/detalhe.html
<!DOCTYPE html>
{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
{% block base_perfil %}
{% endblock %}
    {% block base_login_registar %}
    {% endblock %}

{% block base_index %}

<h1> Questão: {{ questao.questao_texto }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

{% if questao.opcao_set.all.count != 0 %}
<form action="{% url 'votacao:voto' questao.id %}" method="post">
    {% csrf_token %}
    {% for opcao in questao.opcao_set.all %}
        <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}" />
        <label for="opcao{{ forloop.counter }}">{{ opcao.opcao_texto }}</label>
    <br />
    {% endfor %}
    <br />
    <input type="submit" value="Votar" />
    {% if request.user.is_superuser %}
        <input type="submit" value="Remover opcao" formaction="{% url 'votacao:removeropcao' questao.id %}"/>
    {% endif %}
</form>
{% else %}
    <p>Não existem opções associadas a esta questão</p>
{% endif %}

<br/>

{% if request.user.is_superuser %}
    <form action="{% url 'votacao:criaropcao' questao.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Adicionar uma nova opcao" /><br><br>
        <input type="submit" value="Apagar questao" formaction="{% url 'votacao:removerquestao' questao.id %}"/>
    </form>
{% endif %}

<ul>
    {% if questao.opcao_set.all.count != 0 %}
        <a href="{% url 'votacao:resultados' questao.id %}">Contagem dos votos</a><br>
    {% endif %}
    <a href="{% url 'votacao:index' %}">Retornar ao Index</a>
</ul>

{% endblock %}

</body>

</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/fazer_upload.html
<!DOCTYPE html>
{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block base_perfil %}
    {% endblock %}
    {% block base_login_registar %}
    {% endblock %}
    {% block base_index %}
 <form method="post" enctype="multipart/form-data" action="{% url 'votacao:fazer_upload' %}">
 {% csrf_token %}
     <br/>
     <input type="file" name="myfile">
     <br/>
     <input type="submit" value="Upload">
 </form>

 {% if uploaded_file_url %}
    <p>Feito o upload para:<a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
 {% endif %}
    <p><a href="{% url 'votacao:perfil' %}">Voltar ao perfil</a></p>
    <p><a href="{% url 'votacao:index' %}">Voltar ao Index</a></p>
    {% endblock %}

</body>
</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/index.html
<!DOCTYPE html>

{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pagina inicial</title>
</head>

<body>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'votacao/style.css' %}" />

{% block base_perfil %}
{% endblock %}

{% block base_login_registar %}
{% endblock %}

{% block base_index %}
<main>
<article>
    <h1>Lista de questões</h1>
    {% if request.user.is_superuser %}
        <a href="{% url 'votacao:criarquestao' %}">Criar nova questao</a>
    {% endif %}

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

{% if latest_question_list %}
<ul>
    {% for questao in latest_question_list %}
        <li>
            <a href="{% url 'votacao:detalhe' questao.id %}">{{ questao.questao_texto }}</a>
        </li>
    {% endfor %}
</ul>

{% else %}
    <p>Nao ha questoes disponiveis.</p>
{% endif %}
</article>
</main>

{% endblock %}


</body>
</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/login.html
<!DOCTYPE html>
{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    {% block base_perfil %}
    {% endblock %}
    {% block base_body %}
    {% endblock %}
    {% block base_index %}

<h1>Login</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'votacao:loginview' %}" method="post">
    {% csrf_token %}
    <label>Escreva o seu nome de utilizador: </label>
    <input type="text" name="username" required/>
    <br/>
    <label>Escreva o sua password: </label>
    <input type="text" name="password" required/>
    <br/>
    <input type="submit" value="Fazer login"/>
</form>
<br>
    <a href="{% url 'votacao:index' %}">Voltar ao Index</a>
    {% endblock %}
</body>
</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/meu_perfil.html
<!DOCTYPE html>
{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>O meu perfil</title>
</head>
<body>
    {% block base_login_registar %}
    {% endblock %}

    {% block base_body %}
    {% endblock %}
    {% block base_index %}

<h1>O meu Perfil</h1>
{% if request.user.is_authenticated%}
    <p> Nome do Utilizador: {{request.user.username}}</p>
    <p> Email do Utilizador: {{request.user.email}}</p>
    <p> Curso do Utilizador: {{request.user.aluno.curso}}</p>
    <p> Número total de votos realizados: {{request.user.aluno.numvotos}}</p>
    <p><a href="{% url 'votacao:fazer_upload' %}"> Fazer Upload de uma imagem </a></p>
    <a href="{% url 'votacao:index' %}"> Retornar ao Menu </a>
{% else %}
    <p>Erro: Não foi feito login.</p>
    <a href="{% url 'votacao:index' %}"> Retornar ao Index para fazer o Login </a>
{%endif%}
    {% endblock %}

</body>

</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/registar.html
<!DOCTYPE html>
{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Novo user</title>
</head>
<body>
    {% block base_perfil %}
{% endblock %}
    {% block base_body %}
    {% endblock %}
    {% block base_index %}
<h1> Registar novo utilizador </h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'votacao:registaruser' %}" method="post">
    {% csrf_token %}
    <label>Escreva o seu nome: </label>
    <input type="text" name="novouser" required/>
    <br/>
    <label>Escreva o seu email: </label>
    <input type="text" name="novouseremail" required/>
    <br/>
    <label>Escreva o sua password: </label>
    <input type="text" name="novouserpassword" required/>
    <br/>
    <label>Escreva o seu curso: </label>
    <input type="text" name="novousercurso" required/>
    <br/><br/>
    <input type="submit" value="Guardar user"/>
</form>
        <br/>
    <a href="{% url 'votacao:index' %}">Voltar ao Index</a>
    {% endblock %}

</body>
</html>

Semana 7/Tiago/siteiscte/votacao/templates/votacao/resultados.html
<!DOCTYPE html>
{% extends "votacao/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block base_perfil %}
    {% endblock %}
    {% block base_login_registar %}
    {% endblock %}
    {% block base_index %}
<h1> Questão: {{ questao.questao_texto }}</h1>
<ul>
    {% for opcao in questao.opcao_set.all %}
<li>
    {{ opcao.opcao_texto }} -- {{ opcao.votos }}
    voto{{ opcao.votos|pluralize }}</li>
{% endfor %}
</ul>
        <a href="{% url 'votacao:detalhe' questao.id %}">Retornar a questão?</a>
        <p><a href="{% url 'votacao:index' %}">Voltar ao Index</a></p>

    {% endblock %}

</body>
</html>