Semana 5/Tiago/siteiscte/votacao/urls.py
from django.urls import include, path
from . import views

app_name = 'votacao'

urlpatterns = [
    # ex: votacao/
    path("", views.index, name='index'),
    # ex: votacao/1
    path('<int:questao_id>', views.detalhe, name='detalhe'),
    # ex: votacao/3/resultados
    path('<int:questao_id>/resultados', views.resultados, name='resultados'),
    # ex: votacao/5/voto
    path('<int:questao_id>/voto', views.voto, name='voto'),

    # criar uma nova questao
    path('criarquestao', views.criarquestao, name='criarquestao'),
    path('adicionarquestao', views.adicionarquestao, name='adicionarquestao'),

    # criar nova opçao para uma questao
    path('<int:questao_id>/criaropcao', views.criaropcao, name='criaropcao'),
    path('<int:questao_id>/adicionaropcao', views.adicionaropcao, name='adicionaropcao'),

    path('<int:questao_id>/removerquestao', views.removerquestao, name='removerquestao'),
    path('<int:questao_id>/removeropcao', views.removeropcao, name='removeropcao'),

]

Semana 5/Tiago/siteiscte/votacao/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
from six import string_types
import datetime


class Questao(models.Model):
    questao_texto = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.questao_texto

    def foi_publicada_recentemente(self):
        return self.pub_data >= timezone.now() - datetime.timedelta(days=1)


class Opcao(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.opcao_texto

Semana 5/Tiago/siteiscte/votacao/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from .models import Questao, Opcao


def criarquestao(request):
    return render(request, 'votacao/criarquestao.html')


def adicionarquestao(request):
    x = Questao(questao_texto=request.POST['novaquestao'], pub_data=timezone.now())
    x.save()
    return HttpResponseRedirect(reverse('votacao:index'))


def criaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/criaropcao.html', {'questao': questao})


def adicionaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    questao.opcao_set.create(opcao_texto=request.POST['adicionaropcao'], votos=0)
    return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))


def removerquestao(request, questao_id):
    # remover a questao e remover as opçoes associadas
    # adicionar if para ver se existe uma opçao associada a questao que quer apagar
    questao = get_object_or_404(Questao, pk=questao_id)
    if questao.opcao_set.count() > 0:
        for opcao in questao.opcao_set.all():
            opcao.delete()
    questao.delete()
    return HttpResponseRedirect(reverse('votacao:index'))


def removeropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'votacao/detalhe.html', {
            'questao': questao,
            'error_message': "Não escolheu uma opção",
        })
    else:
        opcao_seleccionada.delete()
    return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))


def index(request):
    latest_question_list = Questao.objects.order_by('-pub_data')[:5]
    # template = loader.get_template('votacao/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    #  return HttpResponse(template.render(context, request))
    return render(request, 'votacao/index.html', context)


def detalhe(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/detalhe.html', {'questao': questao})


def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/resultados.html', {'questao': questao})


def voto(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html', {
            'questao': questao,
            'error_message': "Não escolheu uma opção",
        })
    else:
        opcao_seleccionada.votos += 1
        opcao_seleccionada.save()
    return HttpResponseRedirect(
        reverse('votacao:resultados', args=(questao.id,)))

Semana 5/Tiago/siteiscte/votacao/templates/votacao/criaropcao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Adicionar uma nova opcao</h1>
<p></p>

<form action="{% url 'votacao:adicionaropcao' questao.id %}" method="post">
    {% csrf_token %}
    <label>Escreva uma opçao: </label><br>
    <input type="text" name="adicionaropcao" />
    <br/>
    <input type="submit" value="Guardar Opcao" />
</form>

</body>
</html>

Semana 5/Tiago/siteiscte/votacao/templates/votacao/criarquestao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Adicionar uma nova questao</h1>

<form action="{% url 'votacao:adicionarquestao' %}" method="post">
    {% csrf_token %}
    <label>Escreva uma pergunta: </label>
    <br>
    <input type="text" name="novaquestao"/>
    <br/>
    <input type="submit" value="Guardar Questao"/>
</form>

</body>
</html>

Semana 5/Tiago/siteiscte/votacao/templates/votacao/detalhe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ questao.questao_texto }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'votacao:voto' questao.id %}" method="post">
    {% csrf_token %}
    {% for opcao in questao.opcao_set.all %}
        <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}" />
        <label for="opcao{{ forloop.counter }}">{{ opcao.opcao_texto }}</label>
    <br />
    {% endfor %}
    <input type="submit" value="Voto" />
    <input type="submit" value="Remover opcao" formaction="{% url 'votacao:removeropcao' questao.id %}"/>
</form>

<br/>

<form action="{% url 'votacao:criaropcao' questao.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Adicionar uma nova opcao" />
</form>
<br/>
<form action="{% url 'votacao:removerquestao' questao.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Apagar questao" />
</form>

</body>
</html>

Semana 5/Tiago/siteiscte/votacao/templates/votacao/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_question_list %}
<ul>
    {% for questao in latest_question_list %}
        <li>
            <a href="{% url 'votacao:detalhe' questao.id %}">
                {{ questao.questao_texto }}</a>
        </li>
    {% endfor %}
</ul>
{% else %}
    <p>Nao ha questoes disponiveis.</p>
{% endif %}

    <a href="{% url 'votacao:criarquestao' %}">Criar nova questao</a>

</body>
</html>