Semana 5/flop/sitegoat/votacao/urls.py
from django.urls import include, path
from . import views

# (. significa que importa views da mesma directoria)
app_name = 'votacao'
urlpatterns = [
# ex: votacao/
    path("", views.index, name='index'),
 # ex: votacao/1
    path('<int:questao_id>', views.detalhe,name='detalhe'),
 # ex: votacao/3/resultados
    path('<int:questao_id>/resultados',views.resultados, name='resultados'),
 # ex: votacao/5/voto
    path('<int:questao_id>/voto', views.voto,name='voto'),

    path('criarquestao', views.criarquestao, name='criarquestao'),

    path('submeterquestao', views.submeterquestao, name='submeterquestao'),

    path('<int:questao_id>/criarvoto', views.criarvoto, name='criarvoto'),

    path('<int:questao_id>/apagarvoto', views.apagarvoto, name='apagarvoto'),

    path('<int:questao_id>/jjkvoto', views.jjkvoto, name='jjkvoto'),

    path('<int:questao_id>/submetervoto', views.submetervoto, name='submetervoto'),
]

Semana 5/flop/sitegoat/votacao/models.py
from django.db import models
from django.utils import timezone
from six import string_types
import datetime

class Questao(models.Model):
    questao_texto = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data de publicacao')
    def __str__(self):
        return self.questao_texto

    def recente(self):
        return self.pub_data >= timezone.now() - datetime.timedelta(days=1)

class Opcao(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return self.opcao_texto

# Create your models here.

Semana 5/flop/sitegoat/votacao/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.utils import timezone

from .models import Questao, Opcao
from django.template import loader
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def index(request):
    latest_question_list =Questao.objects.order_by('-pub_data')[:5]
    context = {'latest_question_list':latest_question_list}
    return render(request, 'votacao/index.html',context)

def criarquestao(request,):
    return render(request, 'votacao/criarquestao.html')

def criarvoto(request,questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    context = {'questao': questao}
    return render(request, 'votacao/criarvoto.html',context)

def apagarvoto(request,questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    context = {'questao': questao, 'opcao': opcao_seleccionada}

    return render(request, 'votacao/apagarvoto.html',context)

def jjkvoto(request,questao_id, opcao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    opcao_seleccionada = questao.opcao_set.get(pk=opcao_id)
    opcao_seleccionada.delete()
    return detalhe(request, questao_id)

def detalhe(request, questao_id):

    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/detalhe.html', {'questao': questao})
def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request,'votacao/resultados.html',{'questao': questao})


def voto(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada =questao.opcao_set.get(pk=request.POST['opcao'])

    except (KeyError, Opcao.DoesNotExist):
    # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html', {
            'questao': questao,
            'error_message': "Não escolheu uma opção",
        })
    else:
        opcao_seleccionada.votos += 1
        opcao_seleccionada.save()
     # Retorne sempre HttpResponseRedirect depois de
     # tratar os dados POST de um form
     # pois isso impede os dados de serem tratados
     # repetidamente se o utilizador
     # voltar para a página web anterior.
    return HttpResponseRedirect(reverse('votacao:resultados',args=(questao.id,)))


def submeterquestao(request):
    questaotexto = request.POST['resposta']
    q= Questao(questao_texto=questaotexto, pub_data=timezone.now())
    q.save()
    return index(request)

def submetervoto(request,questao_id):

    opcaotexto = request.POST['resposta']
    q=get_object_or_404(Questao, pk=questao_id)
    Opcao.objects.create(questao=q,opcao_texto=opcaotexto, votos = 0)


    return detalhe(request, q.id)

"""
def submeterquestao(request):
    if request.method == 'POST':
        questaotexto = request.POST.get('questaotexto', '')  # Safely get questaotexto from POST data
        print(questaotexto)

        if questaotexto:  # Check if questaotexto is not empty
            q = Questao(questao_texto=questaotexto, pub_data=timezone.now())
            q.save()
            return index(request)  # Assuming 'index' is the name of your index view
        else:
            # Handle case where questaotexto is empty
            print(teste)
            return index(request)

    else:
        # Handle GET request (if needed)
        return index(request)
"""

Semana 5/flop/sitegoat/votacao/templates/votacao/apagarvoto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>APAGARVOTO</title>
</head>
<body>

    <h1>APGAR {{ questao.questao_texto }}</h1>

    <a href="{% url 'votacao:detalhes' questao.id  %}"><button type="button"> Voltar!  </button></a>
    <a href="{% url 'votacao:jjkvoto' questao.id opcao.id %}"><button type="button"> Apagar!  </button></a>

</body>
</html>

Semana 5/flop/sitegoat/votacao/templates/votacao/criarquestao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CRIARQUESTA</title>
</head>
<body>
    <h1>Insira texto da questão:</h1>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'votacao:submeterquestao' %}" method="post">
        {% csrf_token %}
         <input type="hidden" name="questaotexto" value="{{ questaotexto }}">

        <input type="text" name="resposta">
        <input type="submit" value="Criar"/>
    </form>
</body>
</html>

Semana 5/flop/sitegoat/votacao/templates/votacao/criarvoto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CRIARVOTO</title>
</head>
<body>
     <h1>Insira texto da opção {{ questao.questao_texto }}:</h1>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'votacao:submetervoto' questao.id %}" method="post">
        {% csrf_token %}

        <input type="text" name="resposta">
        <input type="submit" value="Criar"/>
    </form>
</body>
</html>

Semana 5/flop/sitegoat/votacao/templates/votacao/detalhe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DETALHE</title>
</head>
<body>

    <h1>{{ questao.questao_texto }}</h1>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'votacao:voto' questao.id %}" method="post">
        {% csrf_token %}
        {% for opcao in questao.opcao_set.all %}
        <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}"/>

        <label for="opcao{{ forloop.counter }}">
            {{ opcao.opcao_texto }}
        </label>
        <br/>
        {% endfor %}
        <input type="submit" value="Voto"/>
    </form>
    <a href="{% url 'votacao:criarvoto' questao.id  %}"><button type="button"> Criar opção!  </button></a>
    <a href="{% url 'votacao:apagarvoto' questao.id  %}"><button type="button"> Apagar opção!  </button></a>
</body>
</html>

Semana 5/flop/sitegoat/votacao/templates/votacao/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>INDEX</title>
</head>
<body>
    {% if latest_question_list %}
    <ul>
        {% for questao in latest_question_list %}
        <li>
            <a href="{% url 'votacao:detalhe' questao.id %}">
                {{ questao.questao_texto }}
            </a>
        </li>
        {% endfor %}

    </ul>
    {% else %}
    <p>Nao ha questoes disponiveis.</p>
    {% endif %}
    <div>
        <a href="{% url 'votacao:criarquestao'  %}"><button type="button"> Criar questão!  </button></a>
    </div>
</body>
</html>

Semana 5/flop/sitegoat/votacao/templates/votacao/resultados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ questao.questao_texto }}</h1>
    <ul>
    {% for opcao in questao.opcao_set.all %}
        <li>{{ opcao.opcao_texto }} -- {{ opcao.votos }} voto{{ opcao.votos|pluralize }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'votacao:detalhe' questao.id %}">Votar novamente?</a>
</body>
</html>