Semana 9/Tiago/sitegoat/sitegoat/urls.py
from django.urls import include, path
from django.contrib import admin

from . import views

urlpatterns = [
 path("", views.index, name='index'),
 path('votacao/', include('votacao.urls')),
 path('admin/', admin.site.urls),

]

Semana 9/Tiago/sitegoat/votacao/urls.py
from django.urls import path

from sitegoat.views import LoginView
from . import views

app_name = 'votacao'

# (. significa que importa views da mesma directoria)

urlpatterns = [

    # ex: votacao/
    path("", views.index, name='index'),

    path("uploadpp", views.uploadpp, name='uploadpp'),

    path("loadLogin", views.loadLogin, name='loadLogin'),
    path("loginPage", views.loginPage, name='loginPage'),

    path("userPage", views.userPage, name='userPage'),
    path("logoutview", views.logoutview, name='logoutview'),

    path("registar", views.registar, name='registar'),
    path("loadRegistar", views.loadRegistar, name='loadRegistar'),

    # ex: votacao/1
    path('<int:questao_id>', views.detalhe, name='detalhe'),
    # ex: votacao/3/resultados
    path('<int:questao_id>/resultados', views.resultados, name='resultados'),
    # ex: votacao/5/voto
    path('<int:questao_id>/trataropcao', views.trataropcao, name='trataropcao'),

    # criar questao
    path('criarquestao', views.criarquestao, name='criarquestao'),
    # submeter questao
    path('submeterquestao', views.submeterquestao, name='submeterquestao'),

    # criar opcao
    path('<int:questao_id>/criaropcao', views.criaropcao, name='criaropcao'),
    # submeter opcao
    path('<int:questao_id>/submeteropcao', views.submeteropcao, name='submeteropcao'),

    # apagar questao
    path('<int:questao_id>/deletequestao', views.deletequestao, name='deletequestao'),

    path('login/', LoginView.as_view(), name='login'),
]

Semana 9/Tiago/sitegoat/votacao/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# def loginview(request):
#    username = request.POST['username']
#    password = request.POST['password']
#    user = authenticate(username=username,
#                        password=password)
#    if user is not None:
#        login(request, user)
#    else:

class Aluno(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    curso = models.CharField(max_length=100)
    votosmax = models.IntegerField()
    votos = models.IntegerField(default=0)
    profile_picture = models.CharField(max_length=100)


class Questao(models.Model):
    objects = None
    questao_texto = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.questao_texto

    def recente(self):
        return self.pub_data >= timezone.now() - datetime.timedelta(days=1)


class Opcao(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.opcao_texto

Semana 9/Tiago/sitegoat/votacao/views.py
import django.contrib.auth.models
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from .models import Questao, Opcao, Aluno
from django.contrib.auth import authenticate, login, logout


def index(request):
    latest_question_list = Questao.objects.order_by('-pub_data')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'votacao/index.html', context)


def not_LogIn(user):
    return not user.is_authenticated


@user_passes_test(not_LogIn, login_url='/votacao/userPage')
def loginPage(request):
    return render(request, 'votacao/loginPage.html')


@user_passes_test(not_LogIn, login_url='/votacao/userPage')
def loadLogin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('votacao:index'))
    else:
        return render(request, 'votacao/loginPage.html', {'error_message': "Este utilizador não existe."})


@user_passes_test(not_LogIn, login_url='/votacao/userPage')
def registar(request):
    return render(request, 'votacao/registar.html')


@user_passes_test(not_LogIn, login_url='/votacao/userPage')
def loadRegistar(request):
    username = request.POST['username']
    try:
        if User.objects.get(username=username):
            return render(request, 'votacao/registar.html', {'error_message': "Este Utilizador já existe."})
    except django.contrib.auth.models.User.DoesNotExist:
        _ = None
    curso = request.POST['curso']
    try:
        aux = curso.split('-')[1].isdigit()
    except ValueError and IndexError:
        aux = False
    if not aux:
        return render(request, 'votacao/registar.html',
                      {'error_message': "Curso necessita estar no formato: (Nome)-(Número de Turma)."})
    else:
        nums = [*curso.split('-')[1]]
        password = request.POST['password']
        email = request.POST['email']
        user = User.objects.create_user(username=username, email=email, password=password)
        Aluno.objects.create(user=user, votosmax=int(nums[len(nums) - 1]) + 5)
        login(request, user)
        return index(request)


@login_required(login_url='/votacao/loginPage')
def userPage(request):
    return render(request, 'votacao/userPage.html')


@login_required(login_url='/votacao/loginPage')
def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('votacao:index'))


@login_required(login_url='/votacao/loginPage')
def trataropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html', {'questao': questao, 'error_message': "Não escolheu uma opção"})
    else:
        value = request.POST['value']
        if value == "Voto":
            user = request.user.aluno
            if user.votos != user.votosmax:
                user.votos += 1
                user.save()
                opcao_seleccionada.votos += 1
                opcao_seleccionada.save()
                context = {'questao': questao}
            else:
                context = {'questao': questao, 'error_message': "Não pode fazer mais votos."}
            return render(request, 'votacao/resultados.html', context)
        else:
            opcao_seleccionada.delete()
            return render(request, 'votacao/detalhe.html', {'questao': questao})


@login_required(login_url='/votacao/loginPage')
def detalhe(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    if request.user.is_authenticated:
        return render(request, 'votacao/detalhe.html', {'questao': questao})
    else:
        return render(request, 'votacao/resultados.html', {'questao': questao})


def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/resultados.html', {'questao': questao})


@login_required(login_url='/votacao/loginPage')
@permission_required("superuser", login_url='/votacao')
def criarquestao(request):
    return render(request, 'votacao/criarquestao.html')


@permission_required("superuser", login_url='/votacao')
def submeterquestao(request):
    questaotexto = request.POST.get('questaotexto')
    if questaotexto == '':
        return render(request, 'votacao/criarquestao.html', {'error_message': "Não escreveu nenhuma Questão."})
    else:
        q = Questao.objects.create(questao_texto=questaotexto, pub_data=timezone.now())
        q.save()
        return HttpResponseRedirect(reverse('votacao:index'))


@permission_required("superuser", login_url='/votacao')
def criaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/criaropcao.html', {'questao': questao})


@permission_required("superuser", login_url='/votacao')
def submeteropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    opcaotexto = request.POST.get('opcaotexto')
    if opcaotexto == '' or opcaotexto is None:
        return render(request, 'votacao/criaropcao.html',
                      {'questao': questao, 'error_message': "Não escreveu nenhuma Opção."})
    else:
        o = Opcao.objects.create(questao=questao, opcao_texto=opcaotexto, votos=0)
        o.save()
        return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))


@permission_required("superuser", login_url='/votacao')
def deletequestao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    questao.delete()
    return HttpResponseRedirect(reverse('votacao:index'))


@permission_required("superuser", login_url='/votacao')
def deleteopcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html', {'questao': questao, 'error_message': "Não escolheu uma opção"})
    else:
        opcao.delete()
        opcao.save()
        # Retorne sempre HttpResponseRedirect depois de
        # tratar os dados POST de um form
        # pois isso impede os dados de serem tratados
        # repetidamente se o utilizador
        # voltar para a página web anterior.
    return render(request, 'votacao/detalhe.html', {'questao': questao})


@login_required(login_url='/votacao/loginPage')
def uploadpp(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        user = request.user.aluno
        if user.profile_picture:
            print("silly")
            filename = user.profile_picture
            fs.delete(filename.split("/")[1])
        filename = fs.save(myfile.name, myfile)
        user.profile_picture = "media/" + filename
        user.save()
        return render(request, 'votacao/userPage.html', {'uploaded_file_url': "media/" + filename})
    return render(request, 'votacao/userPage.html', {'error_message': "Não escolheu nenhum ficheiro."})

Semana 9/Tiago/sitegoat/votacao/templates/votacao/criaropcao.html
<!DOCTYPE html>
<html>

    {% extends "votacao/index.html" %}


    {% block title %}Criar Opção{% endblock %}


    {% block header_title %}{{questao.questao_texto}}{% endblock %}


    {% block body %} <article> <body>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form action="{% url 'votacao:submeteropcao' questao.id %}" method="post">
            {% csrf_token %}
            <label> Escreva a sua Opção: <br>
                <input class="form1" type="text" name="opcaotexto" value="{{ opcaotexto }}" />
            </label>
            <br> <br>
            <input class="button2" type="submit" value="Submeter" />
        </form>

    </body> </article> {% endblock %}

</html>

Semana 9/Tiago/sitegoat/votacao/templates/votacao/criarquestao.html
<!DOCTYPE html>
<html>

    {% extends "votacao/index.html" %}


    {% block title %}Criar Questão{% endblock %}


    {% block header_title %}Criar Nova Questão{% endblock %}


    {% block body %} <article> <body>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form action="{% url 'votacao:submeterquestao' %}" method="post">
            {% csrf_token %}
            <label> Texto da Questão: <br>
                <input class="form1" type="text" name="questaotexto" value="{{ questaotexto }}" />
            </label>
            <br> <br>
            <input class="button2" type="submit" value="Submeter" />
        </form>

    </body> </article> {% endblock %}

</html>

Semana 9/Tiago/sitegoat/votacao/templates/votacao/detalhe.html
<!DOCTYPE html>
<html>

    {% extends "votacao/index.html" %}


    {% block title %}Questão {{questao.id}}{% endblock %}


    {% block header_title %}{{ questao.questao_texto }}{% endblock %}


    {% block nav %}
        <br>
        <p class="dotdiv"> </p>
        <br>
        <a href="{% url 'votacao:criaropcao' questao.id %}"><button class="button1">Adicionar Opção</button></a>
        <br>
        <a href="{% url 'votacao:deletequestao' questao.id %}"><button class="button1">Apagar Questão</button></a>
    {% endblock %}


    {% block body %} <article> <body>

        <br>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form method="post"  action="{% url 'votacao:trataropcao' questao.id %}">
            {% csrf_token %}
            {% for opcao in questao.opcao_set.all %}
            <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}" />
            <label for="opcao{{ forloop.counter }}"> {{ opcao.opcao_texto }} </label>
            <br>
            {% endfor %}
            <br>
            <input class="button2" type="submit" name="value" value="Voto" />
            {% if request.user.is_superuser %}
                <input class="button2" type="submit" name="value" value="Apagar Opção" />
            {% endif %}
            <br>
        </form>

    </body> </article> {% endblock %}

</html>

Semana 9/Tiago/sitegoat/votacao/templates/votacao/index.html
<!DOCTYPE html>
<html>

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Questões{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script>
        $(document).ready(function(){
            $("#imagem").on("dblclick", function() {
                $("#imagem").hide();
            });
            $("#nome").click(function(){
                $("#test").show();
            });
            
            $("#showListQuestion").click(function(){
                $("#list").show();
                $("#hideListQuestion").show();
                $("#showListQuestion").hide();
            });
            
            $("#hideListQuestion").click(function(){
                $("#list").hide();
                $("#showListQuestion").show();
                $("#hideListQuestion").hide();
            });
            
            $('#showUserDetalhes').hover(function() {
                $("#dadosUser").fadeIn('fast');    
                }, function() {$("#dadosUser").fadeOut('fast');
            });
            
            $('#validarComentario').click(function (){
                
                let texto = $('#comentario').val();
                let palavras = texto.split(" ");
                let arrayInsultos = [
                    "abecula","abentesma","achavascado","alimária",
                    "andrajoso", "barregã", "biltre", "cacóstomo",
                    "cuarra", "estólido", "estroso", "estultilóquio", 
                    "nefelibata","néscio", "pechenga", "sevandija", 
                    "somítico", "tatibitate", "xexé", "cheché", "xexelento"];
                
                let existeInsulto = Boolean(false);
                let insulto = 'nenhum';
                
                for(let i = 0; i < palavras.length; i++) {
                    let palavrasmin = palavras[i].toLowerCase();
                    for (let z = 0; z < arrayInsultos.length; z++) {
                        if (palavrasmin === arrayInsultos[z]) {
                            existeInsulto = Boolean(true);
                            insulto = palavrasmin;
                            break;
                        }
                    }
                    if (existeInsulto === true) {
                        break;
                    }
                }
                if (existeInsulto === true) {
                     $("#comentario").val("Por favor insira um cometario");
                }else{
                     $("#alerta_comentario").text("Validado");
                }
            });
        });
    </script>
</head>

<header>
    <h1> <table style="width: 100%">
        <th style="text-align: left; width: 40%">{% block header_title %} Últimas Questões{% endblock %}</th>
        <th style="text-align: right; width: 46%" id = "nome"> {% block header_name %}
            {% if request.user.is_authenticated %}
            {{ request.user}} votos: {{ request.user.aluno.votos }}
            {% else %}
            User
            {% endif %}
        {% endblock %} </th>
         <th style="text-align: center; width: 4%"> {% block profile_pic %}
            {% if request.user.is_authenticated %}
                {% if request.user.aluno.profile_picture %}
                <img id="imagem" style="border: 2px solid black; border-radius: 26px" width="28" height="28" src='{% static request.user.aluno.profile_picture %}'>
                {% else %}
                <img id="imagem" style="border: 2px solid black; border-radius: 26px" width="28" height="28" src='{% static "defaultpp.jpg" %}'>
                {% endif %}
            {% else %}
            <img style="border: 2px solid black; border-radius: 26px" width="28" height="28" src='{% static "defaultpp.jpg" %}'>
            {% endif %}
         {% endblock %} </th>
    </table> </h1>
</header>

<br>

<section>

    {% block body %} <article> <body>
    <button id="showListQuestion">Mostrar lista de Questões</button>
    <button id="hideListQuestion" style="display: none;">Ocultar lista de Questões</button>
    
    {% if latest_question_list %}
    <ul id="list" style="display: none;">
        {% for questao in latest_question_list %}
        <li>
            <a href="{% url 'votacao:resultados' questao.id %}"> {{ questao.questao_texto }} </a>
        </li>
        {% endfor %}
    </ul>
        
    {% else %}
    <p>Nao ha questoes disponiveis.</p>
    {% endif %}
    <a href="{% url 'votacao:criarquestao' %}"><button class="button2">Criar Questão</button></a>

    </body> </article> {% endblock %}

    <nav>

        <br>
        <a href="{% url 'votacao:index' %}"><button class="button1">Página Inicial</button></a>
        <br>
        <a href="{% url 'votacao:userPage' %}"><button class="button1">Perfil</button></a>
        <br>
        <a href="{% url 'votacao:loginPage' %}"><button class="button1">Login</button></a>

        {% block nav %} {% endblock %}

        <br>

    </nav>

</section>

</html>

Semana 9/Tiago/sitegoat/votacao/templates/votacao/loginPage.html
<!DOCTYPE html>
<html>

{% extends "votacao/index.html" %}


{% block title %}Login{% endblock %}


{% block header_title %}Login{% endblock %}
{% block header_name %} {% endblock %}
{% block profile_pic %} {% endblock %}


{% block body %} <article> <body>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'votacao:loadLogin' %}" method="post">
        {% csrf_token %}
        <label> Nome:
            <input class="form1" type="text" name="username" value="{{ username }}" />
        </label>
        <br>
        <label> Password:
            <input class="form1" type="password" name="password" value="{{ password }}" />
        </label>
            <br> <br>
        <input class="button2" type="submit" name="result" value="Entrar" />
    </form>

    <br> <br>

    Não tem conta? Clique em <a href="{% url 'votacao:registar' %}">Registar</a>

</body> </article> {% endblock %}

</html>

Semana 9/Tiago/sitegoat/votacao/templates/votacao/registar.html
<!DOCTYPE html>
<html>

{% extends "votacao/index.html" %}


{% block title %}Registar{% endblock %}


{% block header_title %}Registar{% endblock %}
{% block header_name %} {% endblock %}
{% block profile_pic %} {% endblock %}


{% block body %} <article> <body>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'votacao:loadRegistar' %}" method="post">
        {% csrf_token %}
        <label> Nome: <input class="form1" type="text" name="username" value="{{ username }}" required /> </label>
        <br>
        <label> Email: <input class="form1" type="email" name="email" value="{{ email }}" required /> </label>
        <br>
        <label> Password: <input class="form1" type="password" name="password" value="{{ password }}" required /> </label>
        <br>
        <label> Curso: <input class="form1" type="text" name="curso" value="{{ curso }}" required /> </label>
        <br> <br>

        <input class="button2" type="submit" name="result" value="Registar" />
        </form>

    
    
    <label for="comentario">Comentario:<br>
    <textarea id="comentario" name="comentario" rows="4" cols="50">Insira um comentario</textarea>
    </label>
    <p id="alerta_comentario"></p>

    <input id="validarComentario" type="button" value="Validar Comentario">
</body> </article> {% endblock %}

</html>

Semana 9/Tiago/sitegoat/votacao/templates/votacao/resultados.html
<!DOCTYPE html>
<html>

{% extends "votacao/index.html" %}


{% block title %} Questão {{questao.id}} {% endblock %}


{% block header %} {{ questao.questao_texto }} {% endblock %}


{% block nav %}
        <br>
        <p class="dotdiv"> </p>
        <br>
        <a href="{% url 'votacao:criaropcao' questao.id %}"><button class="button1">Adicionar Opção</button></a>
        <br>
        <a href="{% url 'votacao:deletequestao' questao.id %}"><button class="button1">Apagar Questão</button></a>
{% endblock %}


{% block body %} <article> <body>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <ul>
        {% for opcao in questao.opcao_set.all %}
        <li>{{ opcao.opcao_texto }}: {{ opcao.votos }} voto{{ opcao.votos|pluralize }}
        </li>
        {% endfor %}
    </ul>

    <a href="{% url 'votacao:detalhe' questao.id %}"><button class="button2">Votar</button></a>
</body> </article> {% endblock %}

</html>

Semana 9/Tiago/sitegoat/votacao/templates/votacao/userPage.html
<!DOCTYPE html>
<html>

{% extends "votacao/index.html" %}


{% block title %}Perfil{% endblock %}


{% block header_title %}
    {% load static %}
    
    {% if request.user.aluno.profile_picture %}
    <img id="showUserDetalhes" style="border: 2px solid black; border-radius: 26px" width="28" height="28" src='{% static request.user.aluno.profile_picture %}'>
    {% else %}
    <img id="showUserDetalhes" style="border: 2px solid black; border-radius: 26px" width="28" height="28" src='{% static "defaultpp.jpg" %}'>
    {% endif %}
    {{ request.user }}
{% endblock %}
{% block header_name %} {% endblock %}
{% block profile_pic %} {% endblock %}


{% block nav %}
    <br>
    <p class="dotdiv"> </p>
    <br>
    <a href="{% url 'votacao:logoutview' %}"><button class="button1">Logout</button></a> <br>
{% endblock %}

{% block body %} <aside style="-webkit-flex: 1; flex: 1; -ms-flex: 1"> <body>

    {% load static %}
    <div id = "dadosUser" style="display: none;">
        Email: {{ request.user.email }} <br>
        Curso: {{ request.user.aluno.curso }} <br>
        Votos Feitos: {{ request.user.aluno.votos }} <br>
    </div>
    </body> </aside>

    <aside style="-webkit-flex: 4; flex: 4; -ms-flex: 4"> <body>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form method="post" enctype="multipart/form-data" action="{% url 'votacao:uploadpp' %}">
        {% csrf_token %}
        <input type="file" name="myfile" required> <br>
        {% if uploaded_file_url %}
        Feito o upload para: <br>
        <img width="200" height="200" src='{% static uploaded_file_url %}'>
        {% endif %}
        <br> <input class="button2" type="submit" value="Upload">
    </form>

</body> </aside> {% endblock %}

</html>